name: Etqan
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.3
  cloud_functions: ^5.0.4
  firebase_storage: ^12.1.2
  shared_preferences: ^2.3.1
  http: ^1.2.2
  carousel_slider: ^4.1.1
  provider: ^6.1.2
  image_picker: ^1.1.2



  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.3.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets:
    - assets/login.png
    - assets/tour.png
    - assets/register.png
    - assets/admin.png
    - assets/etqan.png
    - assets/logo.png
    - assets/login1.png
    - assets/ccna.jpg
    - assets/mcsa.jpg
    - assets/photoshop.jpg
    - assets/python.png
    - assets/flutter_logo.png
    - assets/react_native_logo.png
    - assets/python_logo.png
    - assets/angular_logo.png
